services:
  backend:
    build: backend
    ports:
      - "8000:80"
    env_file:
      - backend/.env

  frontend:
    build: frontend
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env